kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sscp-sit-minimal
  namespace: sscp-sit
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - nodes
      - services
      - endpoints
      - namespaces
      - ingresses
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - configmaps
      - events
      - ingresses/status
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sscp-sit-minimal
  namespace: sscp-sit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sscp-sit-minimal
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sscp-sit